apiVersion: batch/v1
kind: Job
metadata:
  name: configure-app-gateway
spec:
  template:
    spec:
      containers:
      - name: azure-cli
        image: mcr.microsoft.com/azure-cli
        command: ["/bin/bash", "-c"]
        args:
          - |
            az network application-gateway probe create \
              --resource-group {{ .Values.resourceGroup }} \
              --gateway-name {{ .Values.gatewayName }} \
              --name {{ .Values.probeName }} \
              --protocol Http \
              --host {{ .Values.hostName }} \
              --path {{ .Values.path }} \
              --interval 30 \
              --timeout 5 \
              --unhealthy-threshold 3
      restartPolicy: Never
